# Generated by Django 4.2.11 on 2026-01-06 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrafficSignal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("N", "North"),
                            ("S", "South"),
                            ("E", "East"),
                            ("W", "West"),
                        ],
                        max_length=1,
                        unique=True,
                    ),
                ),
                (
                    "current_state",
                    models.CharField(
                        choices=[
                            ("RED", "Red"),
                            ("YELLOW", "Yellow"),
                            ("GREEN", "Green"),
                        ],
                        default="RED",
                        max_length=10,
                    ),
                ),
                ("vehicle_count", models.IntegerField(default=0)),
                ("green_time", models.IntegerField(default=30)),
                ("yellow_time", models.IntegerField(default=5)),
                ("red_time", models.IntegerField(default=30)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["direction"],
            },
        ),
        migrations.CreateModel(
            name="TrafficLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_count", models.IntegerField()),
                ("signal_state", models.CharField(max_length=10)),
                ("waiting_time", models.IntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="signal_app.trafficsignal",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
