# Generated by Django 4.2.11 on 2026-01-08 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("signal_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trafficlog",
            name="signal",
            field=models.ForeignKey(
                help_text="Traffic signal related to this log",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="signal_app.trafficsignal",
            ),
        ),
        migrations.AlterField(
            model_name="trafficlog",
            name="signal_state",
            field=models.CharField(
                choices=[("RED", "Red"), ("YELLOW", "Yellow"), ("GREEN", "Green")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="trafficlog",
            name="vehicle_count",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="trafficlog",
            name="waiting_time",
            field=models.PositiveIntegerField(
                default=0, help_text="Time vehicles waited at signal in seconds"
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignal",
            name="current_state",
            field=models.CharField(
                choices=[("RED", "Red"), ("YELLOW", "Yellow"), ("GREEN", "Green")],
                default="RED",
                help_text="Current state of the signal",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignal",
            name="direction",
            field=models.CharField(
                choices=[("N", "North"), ("S", "South"), ("E", "East"), ("W", "West")],
                help_text="Direction of the traffic signal",
                max_length=1,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignal",
            name="green_time",
            field=models.PositiveIntegerField(
                default=30, help_text="Duration of green light in seconds"
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignal",
            name="red_time",
            field=models.PositiveIntegerField(
                default=30, help_text="Duration of red light in seconds"
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignal",
            name="vehicle_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of vehicles currently waiting"
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignal",
            name="yellow_time",
            field=models.PositiveIntegerField(
                default=5, help_text="Duration of yellow light in seconds"
            ),
        ),
    ]
