# Generated by Django 5.2.10 on 2026-01-09 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signal_app", "0002_alter_trafficlog_signal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trafficlog",
            name="waiting_time",
            field=models.PositiveIntegerField(
                default=0, help_text="Waiting time in seconds"
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignal",
            name="green_time",
            field=models.PositiveIntegerField(
                default=30, help_text="Green light duration (seconds)"
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignal",
            name="red_time",
            field=models.PositiveIntegerField(
                default=30, help_text="Red light duration (seconds)"
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignal",
            name="vehicle_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Total number of vehicles currently waiting"
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignal",
            name="yellow_time",
            field=models.PositiveIntegerField(
                default=5, help_text="Yellow light duration (seconds)"
            ),
        ),
        migrations.CreateModel(
            name="SignalTiming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("green_start_time", models.DateTimeField()),
                ("green_end_time", models.DateTimeField()),
                (
                    "total_green_time",
                    models.PositiveIntegerField(
                        help_text="Total green time in seconds"
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timings",
                        to="signal_app.trafficsignal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("two_wheeler", models.PositiveIntegerField(default=0)),
                ("four_wheeler", models.PositiveIntegerField(default=0)),
                ("heavy_vehicle", models.PositiveIntegerField(default=0)),
                ("total_vehicles", models.PositiveIntegerField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_counts",
                        to="signal_app.trafficsignal",
                    ),
                ),
            ],
        ),
    ]
