# Generated by Django 5.2.10 on 2026-01-16 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signal_app", "0003_alter_trafficlog_waiting_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleTypeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("two_wheeler", "Two Wheeler"),
                            ("four_wheeler", "Four Wheeler"),
                            ("heavy_vehicle", "Heavy Vehicle"),
                            ("emergency_vehicle", "Emergency Vehicle"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=1.0,
                        help_text="Weight multiplier for density calculation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="trafficlog",
            name="is_emergency",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trafficlog",
            name="weighted_density",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="trafficsignal",
            name="current_weighted_density",
            field=models.FloatField(
                default=0.0, help_text="Current weighted traffic density score"
            ),
        ),
        migrations.AddField(
            model_name="trafficsignal",
            name="is_emergency_active",
            field=models.BooleanField(
                default=False, help_text="True if emergency override is active"
            ),
        ),
        migrations.AddField(
            model_name="trafficsignal",
            name="mode",
            field=models.CharField(
                choices=[
                    ("ADAPTIVE", "Adaptive AI"),
                    ("EMERGENCY", "Emergency Override"),
                    ("FIXED", "Fixed Timer"),
                    ("MANUAL", "Manual Control"),
                ],
                default="ADAPTIVE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vehiclecount",
            name="emergency_vehicle",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehiclecount",
            name="weighted_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name="EmergencyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("resolved", models.BooleanField(default=False)),
                (
                    "signal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_logs",
                        to="signal_app.trafficsignal",
                    ),
                ),
            ],
        ),
    ]
