# Generated by Django 5.2.10 on 2026-02-08 16:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signal_app", "0004_vehicletypeconfig_trafficlog_is_emergency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trafficsignal",
            name="state_start_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Time when the current state started",
            ),
        ),
        migrations.AlterField(
            model_name="trafficsignal",
            name="red_time",
            field=models.PositiveIntegerField(
                default=10, help_text="Red light duration (seconds)"
            ),
        ),
    ]
