# Generated by Django 5.2.10 on 2026-02-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signal_app", "0005_trafficsignal_state_start_time_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehiclecount",
            options={"ordering": ["timestamp"]},
        ),
        migrations.AddField(
            model_name="emergencylog",
            name="clearance_time",
            field=models.FloatField(
                default=0.0, help_text="Time taken for signal to turn Green (seconds)"
            ),
        ),
        migrations.AddField(
            model_name="vehiclecount",
            name="vehicles_passed",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of vehicles that crossed during this interval",
            ),
        ),
    ]
