# Generated by Django 5.2.10 on 2026-02-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signal_app", "0006_alter_vehiclecount_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehiclecount",
            name="passed_emergency_vehicle",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehiclecount",
            name="passed_four_wheeler",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehiclecount",
            name="passed_heavy_vehicle",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vehiclecount",
            name="passed_two_wheeler",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
