# Generated by Django 5.2.10 on 2026-02-19 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signal_app", "0007_vehiclecount_passed_emergency_vehicle_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Junction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable junction name",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code e.g. JN-001", max_length=20, unique=True
                    ),
                ),
                ("latitude", models.FloatField(default=0.0, help_text="GPS latitude")),
                (
                    "longitude",
                    models.FloatField(default=0.0, help_text="GPS longitude"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="emergencylog",
            options={"ordering": ["-start_time"]},
        ),
        migrations.AddField(
            model_name="emergencylog",
            name="ambulance_id",
            field=models.CharField(
                blank=True,
                help_text="Ambulance unit identifier",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="emergencylog",
            name="ambulance_lat",
            field=models.FloatField(default=0.0, help_text="Ambulance GPS latitude"),
        ),
        migrations.AddField(
            model_name="emergencylog",
            name="ambulance_lng",
            field=models.FloatField(default=0.0, help_text="Ambulance GPS longitude"),
        ),
        migrations.AlterField(
            model_name="trafficsignal",
            name="direction",
            field=models.CharField(
                choices=[("N", "North"), ("S", "South"), ("E", "East"), ("W", "West")],
                help_text="Direction of the traffic signal",
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="AdminActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("MANUAL_OVERRIDE", "Manual Signal Override"),
                            ("TIMING_CONFIG", "Signal Timing Configuration"),
                            ("EMERGENCY_TOGGLE", "Emergency Toggle"),
                            ("SYSTEM_RESET", "System Reset"),
                            ("JUNCTION_CONFIG", "Junction Configuration"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Details of the action performed"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "signal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="signal_app.trafficsignal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="action_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "junction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="signal_app.junction",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AccidentAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("latitude", models.FloatField(default=0.0)),
                ("longitude", models.FloatField(default=0.0)),
                ("is_active", models.BooleanField(default=True)),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "junction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accident_alerts",
                        to="signal_app.junction",
                    ),
                ),
            ],
            options={
                "ordering": ["-reported_at"],
            },
        ),
        migrations.AddField(
            model_name="trafficsignal",
            name="junction",
            field=models.ForeignKey(
                blank=True,
                help_text="Junction this signal belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="signals",
                to="signal_app.junction",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trafficsignal",
            unique_together={("junction", "direction")},
        ),
        migrations.CreateModel(
            name="PollutionReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aqi",
                    models.PositiveIntegerField(
                        default=0, help_text="Air Quality Index (0-500)"
                    ),
                ),
                ("pm25", models.FloatField(default=0.0, help_text="PM2.5 level")),
                ("pm10", models.FloatField(default=0.0, help_text="PM10 level")),
                (
                    "co_level",
                    models.FloatField(default=0.0, help_text="Carbon Monoxide level"),
                ),
                (
                    "no2_level",
                    models.FloatField(default=0.0, help_text="Nitrogen Dioxide level"),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "junction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pollution_readings",
                        to="signal_app.junction",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Admin"), ("operator", "Traffic Operator")],
                        default="operator",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
