# Generated by Django 5.2.10 on 2026-03-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("signal_app", "0008_junction_alter_emergencylog_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("UPLOAD", "Video Upload"), ("LIVE", "Live Camera")],
                        default="UPLOAD",
                        max_length=10,
                    ),
                ),
                (
                    "video_file",
                    models.FileField(blank=True, null=True, upload_to="video_uploads/"),
                ),
                ("total_frames", models.PositiveIntegerField(default=0)),
                ("processed_frames", models.PositiveIntegerField(default=0)),
                ("total_vehicles", models.PositiveIntegerField(default=0)),
                (
                    "density_label",
                    models.CharField(default="Low Traffic", max_length=30),
                ),
                (
                    "lane_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-lane counts and timings",
                    ),
                ),
                (
                    "counts_detail",
                    models.JSONField(
                        blank=True, default=dict, help_text="Vehicle type breakdown"
                    ),
                ),
                ("emergency_detected", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
